In [1]:
import numpy as np

lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
arr = np.array(lst)
arr[arr % 2 != 0] = -2
print(arr)


[[-2  2 -2]
 [ 4 -2  6]
 [-2  8 -2]]


In [3]:
arr = np.array([1,2,3,4,5,8,9,10,12,22,32,54,99,6,7])
print(arr[(arr >= 8) & (arr <= 15)])


[ 8  9 10 12]


In [5]:
arr = np.arange(1, 10).reshape(3, 3)
arr[:, [0, 1]] = arr[:, [1, 0]]
print(arr)


[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [7]:
arr = np.array([[1.3, 2.5, 3.6, np.nan],
                [2.6, 3.3, np.nan, 5.5],
                [2.1, 3.2, 5.4, 6.5]])

# Calculate column-wise mean ignoring NaNs
col_mean = np.nanmean(arr, axis=0)

# Find indices where NaNs are present
inds = np.where(np.isnan(arr))

# Replace NaNs with the respective column means
arr[inds] = np.take(col_mean, inds[1])

print(arr)


[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


In [9]:
arr = np.array([[2, 4, 6], [1, 3, 5]])

# Convert to numpy matrix
matrix = np.matrix(arr)

# Sort the matrix values (row-wise sort)
sorted_matrix = np.sort(matrix, axis=None).reshape(arr.shape)

print("Matrix:")
print(matrix)
print("Sorted Matrix:")
print(sorted_matrix)


Matrix:
[[2 4 6]
 [1 3 5]]
Sorted Matrix:
[[1 2 3]
 [4 5 6]]
