In [ ]:
import pandas as pd
import numpy as np

# Load the CSV file
df = pd.read_csv('SalaryGender.csv')

# Extract each column into a separate NumPy array
salary = df['Salary'].to_numpy()
gender = df['Gender'].to_numpy()
age = df['Age'].to_numpy()
phd = df['PhD'].to_numpy()


In [ ]:
num_men_phd = df[(df['Gender'] == 'Male') & (df['PhD'] == 1)].shape[0]
num_women_phd = df[(df['Gender'] == 'Female') & (df['PhD'] == 1)].shape[0]


In [ ]:
# New DataFrame with Age and PhD
age_phd_df = df[['Age', 'PhD']]

# Remove rows where PhD != 1 from the original DataFrame
df_phd_only = df[df['PhD'] == 1]


In [ ]:
total_phd = df[df['PhD'] == 1].shape[0]


In [3]:
arr = np.array([0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9])
frequency = np.bincount(arr)
print(frequency)
# Output: array([4, 2, 1, 1, 3, 2, 0, 0, 0, 1])


[4 2 1 1 3 2 0 0 0 1]


In [5]:
import numpy as np

arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
filtered = arr[arr > 5]
print(filtered)  # Output: [ 6  7  8  9 10 11]


[ 6  7  8  9 10 11]


In [7]:
arr_with_nan = np.array([np.nan, 1., 2., np.nan, 3., 4., 5.])
clean_arr = arr_with_nan[~np.isnan(arr_with_nan)]
print(clean_arr)  # Output: [1. 2. 3. 4. 5.]


[1. 2. 3. 4. 5.]


In [9]:
random_array = np.random.rand(10, 10)
min_val = np.min(random_array)
max_val = np.max(random_array)
print(f"Min: {min_val}, Max: {max_val}")


Min: 0.005108102100911283, Max: 0.987428770963482


In [11]:
random_vector = np.random.rand(30)
mean_val = np.mean(random_vector)
print(f"Mean: {mean_val}")


Mean: 0.4718389661973078


In [13]:
arr = np.arange(11)
arr[(arr >= 3) & (arr <= 9)] *= -1
print(arr)
# Output: [ 0  1  2 -3 -4 -5 -6 -7 -8 -9 10]


[ 0  1  2 -3 -4 -5 -6 -7 -8 -9 10]


In [15]:
arr = np.random.randint(1, 100, (3, 3))
print("Original array:\n", arr)

# Sort by the first column (index 0)
sorted_by_first = arr[arr[:, 0].argsort()]
print("\nSorted by first column:\n", sorted_by_first)

# Sort by the second column (index 1)
sorted_by_second = arr[arr[:, 1].argsort()]
print("\nSorted by second column:\n", sorted_by_second)

# Sort by the third column (index 2)
sorted_by_third = arr[arr[:, 2].argsort()]
print("\nSorted by third column:\n", sorted_by_third)


Original array:
 [[73 41 89]
 [59  2 19]
 [82 24 70]]

Sorted by first column:
 [[59  2 19]
 [73 41 89]
 [82 24 70]]

Sorted by second column:
 [[59  2 19]
 [82 24 70]
 [73 41 89]]

Sorted by third column:
 [[59  2 19]
 [82 24 70]
 [73 41 89]]


In [17]:
arr4d = np.random.rand(2, 3, 4, 5)  # Shape: (2, 3, 4, 5)

# Sum over the last two axes (axis 2 and 3)
sum_last_two = arr4d.sum(axis=(2, 3))
print("Shape after summing last two axes:", sum_last_two.shape)
print(sum_last_two)


Shape after summing last two axes: (2, 3)
[[ 9.67479914 10.12051185  9.11994235]
 [ 9.04170813  9.46672236  8.97017894]]


In [19]:
import numpy as np

# Create a 4x4 random array
arr = np.random.randint(1, 100, size=(4, 4))
print("Original array:\n", arr)

# Swap row 0 and row 2
arr[[0, 2]] = arr[[2, 0]]
print("\nArray after swapping row 0 and row 2:\n", arr)


Original array:
 [[94 15 19 77]
 [36 83 37 97]
 [68 60 45 85]
 [18 88 68 11]]

Array after swapping row 0 and row 2:
 [[68 60 45 85]
 [36 83 37 97]
 [94 15 19 77]
 [18 88 68 11]]


In [21]:
import numpy as np

# Create a 4x4 random array
arr = np.random.randint(1, 100, size=(4, 4))
print("Original array:\n", arr)

# Swap row 0 and row 2
arr[[0, 2]] = arr[[2, 0]]
print("\nArray after swapping row 0 and row 2:\n", arr)


Original array:
 [[79 65 27 15]
 [49 24 84 87]
 [97 77 52 62]
 [51 61 46 70]]

Array after swapping row 0 and row 2:
 [[97 77 52 62]
 [49 24 84 87]
 [79 65 27 15]
 [51 61 46 70]]
